### ISSUE TITLE
Question about the code 

### ISSUE THREAD

**Issue by lenardxu** [CaoKha/Synchronization#1]
Hi, Caokha. First, many thanks for your sharing the SW-synchronization way of sending image and imu messages. By referring to your code in implementing the SW-synchronization, I have a confusion about this code line (https://github.com/CaoKha/Synchronization/blob/55dc1e0c2a83a288426fd7c2eaf8a0d2a04e9d5a/d435_bno055_interpolation_ros/src/d435_bno055_interpolation_ros_node.cpp#L57) in implementing SW-synchronization of d435 image and bno055 imu messages. Why do you need a 1ms break in the main thread? Doesn't it cause a deviation (delay) of desired time instant in computing the interpolated Imu messages?

**Comment by CaoKha** [comment]
Hi lenardxu, 
if I do recall it right, the `usleep(1000)` is needed to make sure the 2 threads (IMU and camera) were successfully finished their setup before entering the `main` thread (line 59). The camera usually needs time to set up its frame-queue before I could do the interpolation. 
Hope this answers your question.

**Comment by lenardxu** [comment]
> Hi lenardxu, if I do recall it right, the `usleep(1000)` is needed to make sure the 2 threads (IMU and camera) were successfully finished their setup before entering the `main` thread (line 59). The camera usually needs time to set up its frame-queue before I could do the interpolation. Hope this answers your question.
I haven't expected such quick reply. Thx for enlightening me about that.

**Comment by lenardxu** [comment]
> Hi lenardxu, if I do recall it right, the `usleep(1000)` is needed to make sure the 2 threads (IMU and camera) were successfully finished their setup before entering the `main` thread (line 59). The camera usually needs time to set up its frame-queue before I could do the interpolation. Hope this answers your question.

I haven't expected such quick reply. Thx for enlightening me about that.
